export const projects = [
  {
    title: 'NUcamp website',
    description: "Fictional camp website coded with react. You can click on tabs, submit comments, and reviews. The site is interactive.",
      image: '/images/one.png',
      tags: ['React'],
    source: 'https://elegant-yonath-e67447.netlify.app',
    visit: 'https://github.com/janekia/Weather-app',
    id: 0,
  },
  {
    title: 'Weather Application',
    description:"Type in any city and country from anywhere in the world and the app will give you the current temperature (in Celsius) the high and low and also the condition of the sky (cloudy, sunny).",
    image: '/images/2.png',
    tags: ['React', 'JavaScript'],
    source: 'https://nostalgic-blackwell-17e96d.netlify.app',
    visit: 'https://github.com/janekia/Weather-app',
    id: 1,
  },
  {
    title: 'Sass Website',
    description: "A mock website that is styled with sass.",
      image: '/images/3.png',
      tags: ['Sass', 'Javascript'],
    source: 'https://mystifying-shannon-1f0ec2.netlify.app',
    visit: 'https://github.com/janekia/Sass-sample-website',
    id: 2,
  },
  {
    title: 'ToDo List',
    description: "You can add, edit and delete items off your to-do list.",
    image: '/images/4.png',
    tags: ['React'],
    source: 'https://xenodochial-hoover-cf853a.netlify.app',
    visit: 'https://github.com/janekia/To-Do-App',
    id: 3,
  },
  {
    title: 'MP3 Player',
    description: "Music player that can be played and paused. You can also go to the next song or go back to the previous song.",
    image: '/images/5.png',
    tags: ['Html','Css','Javascript'],
    source: 'https://inspiring-torvalds-a1eddc.netlify.app',
    visit: 'https://github.com/janekia/Sample-MP3-player',
    id: 4,
  },
  {
    title: 'Naturally Glow-n Beauty',
    description: "Project I am working on to show off beauty products that are homemade.",
    image: '/images/.png',
    tags: ['Bootstrap'],
    source:'https://ou60wy66m5.execute-api.us-east-2.amazonaws.com/',
    visit: 'https://github.com/janekia/Naturally-Glow-n-Beauty',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2010, text: 'Decided to take a chance on coding.', },
  { year: 2021, text: 'Started coding with Nucamp.', },
  { year: 2022, text: 'A new Grad from Nucamp Bootcamp and ready to start my new career!', },
];
